### ISSUE TITLE
support for the config.bin-dir options in composer.json

### ISSUE THREAD

**Issue by basz** [laminas/laminas-ci-matrix-action#129]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Summary

Tools binaries might be in a different location than `/vendor/bin`.

We could a support for the config.bin-dir options in composer.json

This outputs the current set location.
```
composer config 'bin-dir'
```

**Comment by Ocramius** [comment]
Clear *no* from my end: `vendor/bin` is pretty much ubiquitous, and you should really not mess with that :)

**Comment by basz** [comment]
lol. fine.

```
"post-install-cmd": [
      "rm -f bin && ln -s vendor/bin bin"
],
```
