### ISSUE TITLE
Run psalm against highest PHP version?

### ISSUE THREAD

**Issue by kynx** [laminas/laminas-ci-matrix-action#135]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | sort of
| BC Break    | not sure

#### Summary

While working on https://github.com/laminas/laminas-hydrator/pull/95 I had to completely exclude my new code in psalm.xml, since the component supports PHP 8.0 but the code uses a PHP8.1 feature (enums). I think it would make sense to run Psalm on the highest stable PHP version so new features can be covered.

**Comment by Ocramius** [comment]
Running psalm on the lowest version guarantees that our stuff "keeps working",  and that we didn't accidentally upgrade our users to unsupported features.

It also is in line with our lockfile strategy: if we have a component with `^8.0`, and PHP 8.3 is released, you don't accidentally get broken CI until you bump the minimum supported version.

We cannot run both on lowest and on latest supported versions, as that would require maintaining separate baseline files.

**Comment by Ocramius** [comment]
Practically, as we remove supported versions, the baseline should slowly shrink :)

**Comment by Ocramius** [comment]
Closing: we can't fix this, as running psalm on the newest supported PHP version would make CI much more unstable.
