### ISSUE TITLE
Bump `package.json` to use `node:^19`

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-ci-matrix-action#140]
### Bug Report

As found in #134, we use `node:^18` in `package.json` and `node:19` in `Dockerfile`.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.19.0

NPM happily keeps installing everything with a warning:

```
 #13 1.580 npm WARN EBADENGINE Unsupported engine {
#13 1.581 npm WARN EBADENGINE   package: undefined,
#13 1.581 npm WARN EBADENGINE   required: { node: '^18' },
#13 1.581 npm WARN EBADENGINE   current: { node: 'v19.0.0', npm: '8.19.2' }
#13 1.582 npm WARN EBADENGINE }
```

That's why I kept going and released `1.19.0` anyway: for `1.20.0` we should fix the dependency range.

**Comment by internalsystemerror** [comment]
This should error instead of warn with:

`.npmrc`
```
engine-strict=true
```
