### ISSUE TITLE
Stable PHP version should be changed to PHP 8.0

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-ci-matrix-action#145]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

As of now, stable PHP version default option in this container is PHP 7.4.
Since 7.4 is moved to EOL on [2022-11-28](https://www.php.net/supported-versions.php), we should modify the default PHP version in this container to PHP 8.0 as new stable.

https://github.com/laminas/laminas-ci-matrix-action/blob/e3c605ed21c0bc862458cb4493e7874b420e3e6e/src/config/php.ts#L11

**Comment by internalsystemerror** [comment]
Closed by https://github.com/laminas/laminas-ci-matrix-action/pull/163
