### ISSUE TITLE
JSON Schema for `.laminas-ci.json`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-ci-matrix-action#49]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

This action is currently parsing project configurations and ignores badly formatted jobs while adding a warning to the output.

I would prefer having a check fail. This could be done by creating a JSON Schema along with a Schema validation as done for `composer.json` (as of 1.8.0).

WDYT?

---

We could also add a JSON schema to the container action and re-use it in here for output validation (as part of CI of this container).

**Comment by Ocramius** [comment]
Absolutely on board!

Having a schema definition would totally aid as documentation too :)

**Comment by boesing** [comment]
Implemented in #55
