### ISSUE TITLE
Missing jobs due to incompatibility composer PHP version parser

### ISSUE THREAD

**Issue by ghostwriter** [laminas/laminas-ci-matrix-action#73]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | <=1.11.4

#### Summary

the semver version parser does not work correctly if `composer.json` uses this format `"php": ">=7.4, <8.2"`, which prevents certain jobs from being created.

https://github.com/laminas/laminas-ci-matrix-action/blob/71aa5bef47be3a9d3e1a3865f43caf16708ed847/src/config.js#L25-L39

#### Current behavior

<img src="https://user-images.githubusercontent.com/9754361/149815721-12fd7a7d-428a-41e6-9d1e-828b6dc527f8.png" width="600">

#### How to reproduce

setup a repo with a `composer.json` file with `"require": {"php": ">=7.4, <8.2"}` .

#### Expected behavior

Generate jobs for PHPUnit on PHP `7.4`, `8.0`, & `8.1`

<img src="https://user-images.githubusercontent.com/9754361/149818229-2b425323-ffe5-4ebe-bc3e-d62f9fac725b.png" width="600">

**Comment by boesing** [comment]
Hey, thanks for reporting back.
I am unsure if this is related to this package or to upstream https://github.com/npm/node-semver
We do not implement semver ourselves and thus I'd report it there.

Since there was no update since 03/2021, the current matrix action container should already contain the latest version of `node-semver`.

Do you know any other semver parsing library which could replace the current `semver` dependency in this action?

**Comment by ghostwriter** [comment]
@boesing I believe it is related to this package. We should "normalize" the `Composer` version string `composerJson['require']['php'].replace(/,\s/i, ' ')` to the format `NPM` understands.

### `NPM`
> Advanced ranges may be combined in the same way as primitive comparators using white space (` `) or (`||`). https://docs.npmjs.com/cli/v6/using-npm/semver

eg. https://jubianchi.github.io/semver-check/#/%3E%3D1.2.7%20%3C1.3.0/1.2.8

### `Composer`
>You can define multiple ranges. Ranges separated by a space (` `) or comma (`,`) will be treated as a logical AND. A double pipe (`||`) will be treated as a logical OR. AND has higher precedence than OR.
https://getcomposer.org/doc/articles/versions.md#version-range

eg. https://semver.madewithlove.com/?package=composer%2Fcomposer&constraint=%3E%3D2.1.1%2C+%3C2.2.2&stability=stable

**Comment by Ocramius** [comment]
Thanks @ghostwriter!

**Comment by boesing** [comment]
Got it, thanks for pointing that out @ghostwriter!
