### ISSUE TITLE
Empty or non-existent `ignore_php_platform_requirements` does not disable PHP 8.0 default behavior

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-ci-matrix-action#80]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.11.5

#### Summary

When I've impelemented the `ignore_php_platform_requirements` feature, the main idea was to get rid of the old and yet deprecated `ignore_platform_reqs_8` feature, which defaulted to `true`.

I was assuming (and thought I've implemented it that way 😅) that when adding an empty `ignore_php_platform_requirements` object to the `.laminas-ci.json`, we do not explicitly mark PHP 8.0 as `true`.
Sadly, it does and thus, I'd like to either change this and/or remove `ignore_platform_reqs_8` entirely.

`ignore_php_platform_requirements` option is available since [v1.9.0](https://github.com/laminas/laminas-ci-matrix-action/releases/tag/1.9.0) (released in 08/2021)

#### Current behavior

Adding an empty `ignore_php_platform_requirements` does not prevent ignoring platform reqs for PHP 8.0.

#### How to reproduce

Add an empty `ignore_php_platform_requirements` to the `.laminas-ci.json` in a project with PHP 8.0 support and check matrix output. It contains `ignore_php_platform_requirement: true` for PHP 8.0.

#### Expected behavior

`ignore_php_platform_requirement` should be `false` for PHP 8.0.

**Comment by boesing** [comment]
Well, since we do validate project configs with the `laminas-ci.schema.json` and disallow additional properties, projects containing `ignore_platform_reqs_8` won't work anymore.

So we can safely remove `ignore_platform_reqs_8` but we still should provide some information to the CHANGELOG that platform requirements for PHP 8 are not ignored by default anymore.

**Comment by boesing** [comment]
Input handling will be removed with #83, matrix output stays the same for now.
Disabled PHP 8.0 default ignore behavior.

**Comment by Ocramius** [comment]
I have similar issues related to this (this comment is just informational):

 * https://github.com/Roave/BackwardCompatibilityCheck/runs/6661744285?check_suite_focus=true 
 * https://github.com/Roave/BackwardCompatibilityCheck/runs/6661746931?check_suite_focus=true

They lead to https://github.com/Roave/BackwardCompatibilityCheck/pull/529 failing

The `.laminas-ci.json` is as follows:

```json
{
    "extensions": [
        "bcmath"
    ]
}
```

The generated argument for a "latest dependencies" build:

```
"{\"command\":\"./vendor/bin/phpunit\",\"php\":\"8.0\",\"extensions\":[\"json\",\"bcmath\"],\"ini\":[\"memory_limit        = -1\"],\"dependencies\":\"latest\",\"ignore_platform_reqs_8\":true,\"ignore_php_platform_requirement\":true,\"additional_composer_arguments\":[]}"
```

More specifically:

```
\"dependencies\":\"latest\",\"ignore_platform_reqs_8\":true,\"ignore_php_platform_requirement\":true
```
